name: Publish Android Bindings
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'breez-sdk repo release (MAJOR.MINOR.PATCH)'
        required: true
        type: string

jobs:
  publish-android:
    runs-on: macOS-latest
    steps:
      # - name: Install dependencies
      #   run: |
      #     sudo apt-get install -y protobuf-compiler
      #     cargo install --version 0.22.0 uniffi_bindgen
      #     cargo install cargo-ndk
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.version }}
      - name: Setup SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.REPO_SSH_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions
      # - name: Setup Java
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: temurin
      #     java-version: 11
      # - name: Setup Gradle
      #   uses: gradle/gradle-build-action@v2
      #   with:
      #     gradle-version: 7.3.2
      # - name: Build Android project
      #   env:
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #   run: |
      #     cd libs/sdk-bindings
      #     make init
      #     make bindings-android
      # - name: Publish artifacts
      #   uses: gradle/gradle-build-action@v2
      #   with:
      #     build-root-directory: libs/sdk-bindings/bindings-android
      #     arguments: publish -PlibraryVersion=${{ inputs.version }} -PbreezReposiliteUsername=${{ secrets.BREEZ_MVN_USERNAME }} -PbreezReposilitePassword=${{ secrets.BREEZ_MVN_PASSWORD }}
      - name: Publish artifacts
        run: |
          cd libs/sdk-bindings/bindings-android
          ./gradlew tasks          
          ./gradlew --info --debug publish -PlibraryVersion=${{ inputs.version }}
