name: Publish Python Bindings
on:
  workflow_call:
    inputs:
      repository:
        description: 'sdk repository, defaults to current repository'
        required: false
        type: string
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
      package-version:
        description: 'version for the python package (MAJOR.MINOR.BUILD)'
        required: true
        type: string
      publish:
        description: 'value indicating whether to publish to pypi.'
        required: true
        type: boolean
        default: false
    secrets:
      PYPI_API_TOKEN:
        description: 'api token to authenticate to pypi'
        required: true

jobs:
  build-macos-wheels:
    runs-on: macos-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout breez-sdk repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.sha }}

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/download-artifact@v3
        with:
          name: sdk-bindings-darwin-universal
          path: libs/sdk-bindings/bindings-python/src/breez_sdk

      - uses: actions/download-artifact@v3
        with:
          name: bindings-python
          path: libs/sdk-bindings/bindings-python/src/breez_sdk

      - name: Clean up downloaded files
        run: |
          rm -f libs/sdk-bindings/bindings-python/src/breez_sdk/*.a
          ls -R libs/sdk-bindings/bindings-python

      - name: Update package version
        if: ${{ inputs.package-version }}
        working-directory: libs/sdk-bindings/bindings-python
        run: sed -i.bak -e 's/    version=".*",/    version="${{ inputs.package-version }}",/' setup.py

      - name: Install dependencies
        working-directory: libs/sdk-bindings/bindings-python
        run: pip3 install wheel setuptools

      - name: Build wheel
        working-directory: libs/sdk-bindings/bindings-python
        run: python3 setup.py bdist_wheel --plat-name macosx_11_0_universal2 --verbose

      - name: List wheel contents
        working-directory: libs/sdk-bindings/bindings-python/dist
        run: python3 -m zipfile --list *.whl || true

      - name: Archive the wheel
        uses: actions/upload-artifact@v3
        with:
          name: python-wheel-${{ matrix.python }}-macos
          path: libs/sdk-bindings/bindings-python/dist/*.whl

  build-linux-wheels:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.sha }}

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/download-artifact@v3
        with:
          name: sdk-bindings-${{ matrix.arch }}-unknown-linux-gnu
          path: libs/sdk-bindings/bindings-python/src/breez_sdk

      - uses: actions/download-artifact@v3
        with:
          name: bindings-python
          path: libs/sdk-bindings/bindings-python/src/breez_sdk

      - name: Update package version
        if: ${{ inputs.package-version }}
        working-directory: libs/sdk-bindings/bindings-python
        run: sed -i.bak -e 's/    version=".*",/    version="${{ inputs.package-version }}",/' setup.py

      - name: Install dependencies
        working-directory: libs/sdk-bindings/bindings-python
        run: pip3 install wheel setuptools

      - name: "Build wheel"
        working-directory: libs/sdk-bindings/bindings-python
        run: python3 setup.py bdist_wheel --plat-name manylinux_2_31_${{ matrix.arch }} --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: python-wheel-${{ matrix.python }}-manylinux_2_31_${{ matrix.arch }}
          path: libs/sdk-bindings/bindings-python/dist/*.whl

  publish-package:
    runs-on: ubuntu-latest
    needs: [build-macos-wheels, build-linux-wheels]
    steps:
      - name: Checkout breez-sdk repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.sha }}

      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          path: libs/sdk-bindings/bindings-python/dist/

      - name: Clean downloaded contents
        working-directory: libs/sdk-bindings/bindings-python
        run: |
          find dist -maxdepth 1 ! -path dist ! -name "python-wheel-*" -exec rm -rf {} \;
          ls -laR dist

      # for developing, testing, and experimenting
      # - name: "Publish on test PyPI"
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     verbose: true
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/
      #     packages_dir: libs/sdk-bindings/bindings-python/dist/*/

      - name: "Publish on PyPI"
        if: ${{ inputs.publish }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: libs/sdk-bindings/bindings-python/dist/*/
