name: Publish Swift Bindings
on:
  push:
    branches:
      - publish-rn
  workflow_dispatch:
    inputs:
      version:
        description: 'breez-sdk repo release (MAJOR.MINOR.PATCH)'
        required: true
        type: string
permissions:
  pull-requests: write  
  repository-projects: write
jobs:
  build-tag-release:
    name: Build, tag, and release the Breez SDK React Native package
    runs-on: macos-13
    steps:
      - name: Install required dependencies
        run: |
          brew install protobuf
          cargo install --version 0.22.0 uniffi_bindgen
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.version }}
      - name: Checkout sdk-react-native repo
        uses: actions/checkout@v3
        with:
          repository: breez/breez-sdk-react-native
          ssh-key: ${{ secrets.REPO_SSH_KEY }}
          path: dist
      - name: Build React Native package
        working-directory: libs/sdk-react-native
        env:
          SSH_PRIVATE_KEY: ${{secrets.REPO_SSH_KEY}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          make init
          make all      
      - name: Update Swift Package definition
        working-directory: libs/sdk-react-native
        run: |
          git checkout -b test-ci origin/test-ci          
          cp -r android ../../dist
          cp -r ios ../../dist
          cp -r scripts ../../dist
          cp -r src ../../dist
          cp -r package.json ../../dist
          cp -r yarn.lock ../../dist
          cp -r BreezSDK.podspec.dev ../../dist/BreezSDK.podspec
          rm -f ../../dist/ios/bindings-swift/.gitignore
      - name: Tag the React Native package
        working-directory: dist
        run: |          
          git add -A          
          git commit -m "Update Breez SDK React Native to version ${{ inputs.version }}"
          git push    
